# Generated by Django 4.1 on 2023-12-03 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_page', models.URLField(verbose_name='Ссылка на страницу')),
                ('page_title', models.TextField(blank=True, null=True, verbose_name='Заголовок страницы')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('picture', models.URLField(blank=True, null=True, verbose_name='Картинка превью')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Закладка',
                'verbose_name_plural': 'Закладки',
            },
        ),
        migrations.CreateModel(
            name='LinkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('type', models.CharField(max_length=150, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип ссылки',
                'verbose_name_plural': 'Тип ссылки',
            },
        ),
        migrations.CreateModel(
            name='CollectionBookmarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Название')),
                ('short_description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Краткое описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('bookmarks', models.ManyToManyField(blank=True, related_name='collection', to='bookmarks_manager.bookmarks', verbose_name='Закладки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
            },
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='link_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookmarks_manager.linktype', verbose_name='Тип ссылки'),
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
